Update NDcPP_v2_2e.adoc
ND-iTC/Documents pull request #11
Opened 2021-09-24 23:56 UTC by qtrinh3

Updated fcs_tlss_ext.1.1 in appendix B

2021-10-26 17:28 UTC, mclearn submitted a review, later dismissed

2021-11-05 14:48 UTC, kr15tyk requested changes
@qtrinh3 I believe these edits were only focused on FCS_TLSS_EXT.1.1. Is that correct? I noticed that App note 124 from the MS Word doc is not included.

2021-11-05 14:48 UTC, kr15tyk commented on NDcPP_v2_2e.adoc
>  _In a future version of this cPP TLS v1.2 will be required for all TOEs._
@qtrinh3 Application note 124 in the NDcPP TLSWGProposal_TLSv13_v13d MS Word document is missing from your edits.

2021-11-05 20:15 UTC, ianhallbc approved these changes

2021-11-16 18:29 UTC, kr15tyk approved these changes

2021-11-16 18:31 UTC, merged