Dtls 042822 rw
ND-iTC/Documents pull request #54
Opened 2022-04-28 17:29 UTC by plughy2

Add the RFC for DTLS 1.3 now that is it published by IETF;  Remove DTLS 1.0.

2022-04-30 18:07 UTC, kr15tyk requested changes

2022-05-03 12:32 UTC, plughy2 commented on NDcPP_v2_2e.adoc
> +_The process to validate the DTLS client is specified in section tbd of RFC 9147 (DTLS 1.3) and section 4.2.1 of RFC 6347 (DTLS 1.2). The TOE validates the DTLS client during Connection Establishment
changed section tbd to section 5.1

2022-05-03 13:12 UTC, kr15tyk approved these changes

2022-05-03 16:51 UTC, ouarak approved these changes

2022-05-03 17:59 UTC, merged